Add CLI for cloudkeeper-aws
the-cloudkeeper-project/cloudkeeper-aws pull request #7
Opened 2018-08-21 13:03 UTC by dudoslav

CLI includes method sync and version. Also this commit adds THOR into
dependencies, gem bin folder and also add config file.

2018-08-23 09:23 UTC, amarthadan requested changes

2018-08-23 09:23 UTC, amarthadan commented on lib/cloudkeeper/aws/cli.rb
> +      method_option :'polling-timeout',
Missing option description.

2018-08-23 09:23 UTC, amarthadan commented on lib/cloudkeeper/aws/cli.rb
> +    class CLI < Thor
Missing options for logging and debugging. Is that on purpous? Will that be included in the logging PR?

2018-08-23 09:23 UTC, amarthadan commented on lib/cloudkeeper/aws/cli.rb
> +      def initialize_cloud
What is the point of this method and keeping `Cloudkeeper::Aws::Cloud` as an instance variable? Wouldn't be easier to call `Cloudkeeper::Aws::CoreConnector.new(Cloudkeeper::Aws::Cloud.new)` directly?

2018-08-23 09:23 UTC, amarthadan commented on lib/cloudkeeper/aws/cli.rb
> +      method_option :'polling-timeout',
`cloudkeeper-one` is using gem `chronic_duration` to parse human readable time periods. Maybe you should considre doing the same.

2018-08-23 09:23 UTC, amarthadan commented on lib/cloudkeeper/aws/cli.rb
> +      method_option :authentication,
You should add a check which will see whether when `authentication` option is set to `true` options `certificate`, `key` and `core-certificate` are set as well. This way `TypeError: no implicit conversion of nil into String` would be thrown and that is quite misleading.

Take a look at [https://github.com/the-cloudkeeper-project/cloudkeeper-one/blob/master/lib/cloudkeeper/one/cli.rb#L133](https://github.com/the-cloudkeeper-project/cloudkeeper-one/blob/master/lib/cloudkeeper/one/cli.rb#L133).

2018-08-23 09:23 UTC, amarthadan commented on config/cloudkeeper-aws.yml
>  aws:
What exactly can be set in this section? I thought that we would leave that for the AWS configuration file.

2018-08-27 12:07 UTC, dudoslav commented on lib/cloudkeeper/aws/cli.rb
> +      method_option :'polling-timeout',
I considered it

2018-08-29 11:09 UTC, amarthadan approved these changes
:eagle:

2018-08-29 11:55 UTC, merged